In [1]:
import pandas as pd

In [3]:
p1 = pd.Series([1,2,"akshay",True])
p1

0         1
1         2
2    akshay
3      True
dtype: object

In [4]:
import numpy as np

In [5]:
n1 = np.array([1,2,"akshay",True])
n1

array(['1', '2', 'akshay', 'True'], dtype='<U21')

In [6]:
#pandas gives in series
#pandas have two types of indexing implicit and explicit indexing

In [7]:
a=pd.Series([1,2,3,4,5])#implicit series indexing (pre defined indexes or auto)
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
b=pd.Series([1,2,3,4,5],index=[2,3,4,5,6])#explicit indexing (user defined indexes)
b

2    1
3    2
4    3
5    4
6    5
dtype: int64

In [9]:
a+b

0    NaN
1    NaN
2    4.0
3    6.0
4    8.0
5    NaN
6    NaN
dtype: float64

In [11]:
c=pd.Series([1,2,3,4,5,6],index=[1,2,3,4,5,6])
c

1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64

In [12]:
a+c#as you can see if you perform anyu operation between the series by matcing the indexes
#it gives nan values for unmatched index in a we have 0 th oindex and c has not there so it takes c[0] index as the nan values as we know nan 
#with any operation gives nan
#it converts the values as float becuase of nan values nan dtype is float64

0    NaN
1    3.0
2    5.0
3    7.0
4    9.0
5    NaN
6    NaN
dtype: float64

In [13]:
#we take the same series and we perform the differnrt operations
ser1 =  pd.Series([1,2,3,4])
ser2 = pd.Series([2,3,4,1,1],index=[1,2,3,4,5])
print(ser1)
print(ser2)

0    1
1    2
2    3
3    4
dtype: int64
1    2
2    3
3    4
4    1
5    1
dtype: int64

In [15]:
ser1+ser2

0    NaN
1    4.0
2    6.0
3    8.0
4    NaN
5    NaN
dtype: float64

In [16]:
#lets break it down ser1[0] has the value of 1 and ser2[0] is not there so it takes the ser2[0] has the nan value 
#1+nan is nan so 0 is nan and ser[1] is 2 and ser2[1] is 2 so the 2+2 is 4 but it give the values as 4.0 because of
#nan value nan dtype is float64 it converts all them to float64

In [17]:
ser1 =  pd.Series([1,2,3,4,5])
ser2 = pd.Series([1,2,3,4,5],index=[2,3,4,5,6])
print(ser1)
print(ser2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
2    1
3    2
4    3
5    4
6    5
dtype: int64

In [18]:
#get the values of the 2 from the ser1 and ser2 
ser1[1]

2

In [19]:
#ser2 at 3rd index we have the value of 2
ser2[3]#by default it consider the default explicit indexes

2

In [20]:
#get the values of 3,4,5 using slicing
ser1[2:5]

2    3
3    4
4    5
dtype: int64

In [27]:
#at ser2 the values of 1,4,5 has at indexes 2,3,4 so we use 2:5 by the slicing
print(ser2[2:5])#here explicit indexing not taking default implicit indexing taking as default for slicing
print()
print(ser2[4:7])#its not taking explicit indexing

4    3
5    4
6    5
dtype: int64

6    5
dtype: int64

In [24]:
#using advanced indexing getthe values of the 1,4,5
ser1[[0,3,4]]

0    1
3    4
4    5
dtype: int64

In [25]:
ser2[[2,5,6]]#pandas considering the explicit as default but in slicing it choosing implicit

2    1
5    4
6    5
dtype: int64

In [28]:
#incase of the advanced indexing and indexing pandas choosing the explicit indexing as default
#where as slicing pandas choosing the implicit index as the default
# advanced indexing-->explicit
# indexing-->explicit
# slicing-->implicit

In [29]:
#to get rid of the confusing pandas does not depend on the default index and slicing in pandas we use 
#.loc() for the explicit
#.iloc() #for the implicit

In [30]:
print(ser1)
print(ser2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
2    1
3    2
4    3
5    4
6    5
dtype: int64

In [33]:
#get vaue 2 using .iloc
ser1.iloc[1],ser2.iloc[1]#iloc used for the implicit so in ser2 we gave index as 1

(2, 2)

In [35]:
#.loc
ser1.loc[1],ser2.loc[3]#here for ser1 it has no explicit indexing so it consinder explicit as implicit

(2, 2)

In [37]:
#get the values of 2,3,4 as slicing
ser1.iloc[1:4],ser2.iloc[1:4]#as we know .iloc consider as the implicit

(1    2
 2    3
 3    4
 dtype: int64,
 3    2
 4    3
 5    4
 dtype: int64)

In [38]:
ser1.loc[1:3],ser2.loc[3:5]#iincase of slicing using explicit indexes end index id inclusive/cause it is not number

(1    2
 2    3
 3    4
 dtype: int64,
 3    2
 4    3
 5    4
 dtype: int64)

In [39]:
#get the values of 1,4,5
ser1.iloc[[0,3,4]],ser2.iloc[[0,3,4]]

(0    1
 3    4
 4    5
 dtype: int64,
 2    1
 5    4
 6    5
 dtype: int64)

In [40]:
ser1.loc[[0,3,4]],ser2.loc[[2,5,6]]

(0    1
 3    4
 4    5
 dtype: int64,
 2    1
 5    4
 6    5
 dtype: int64)

DATAFRAME

In [41]:
#creating a dataframe pd.DataFrame(  data   )
                                       #/_>list/tuple/nested lists/nested tuple/a list opf strings and list of tuples
#dictionary and nested dictionary
#series and nested series
#dict of lists

popular ways to create is dict of series ,dict of dict,dict of lists

creating a dataframe

In [42]:
df=pd.DataFrame([0,1,2,3,4])
df

   0
0  0
1  1
2  2
3  3
4  4

In [44]:
#creating a data frame using nested list
df2 =  pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df2

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

#every element in list as consider as a row of the dataframe when u are creating with the nested lists
the size of internal lists size are must be same to get rid of nan
if it is not same those values are filled with the nan values

In [45]:
#every element of a list is consider as the row of a dataframe as we see in df example

In [47]:
df3 =  pd.DataFrame([[1,2,3],[4,5,6],[7,8,9,10]])#the internal lists size are not same so it consider as the nan 
df3

   0  1  2     3
0  1  2  3   NaN
1  4  5  6   NaN
2  7  8  9  10.0

creating a data frame using dictionary

In [48]:
#whenever creating data frame using dictionary the keys of the dictionary is consider as the coloumn indexes and the values
#of the dict is col val
#here no need to provide the col name explicitly

{'a': 1, 'b': 2, 'c': 3}

In [52]:
dict = {'a':[1,2,3],'b':[2,3,4],'c':[3,4,5]}

In [53]:
df4 = pd.DataFrame(dict)

In [54]:
df4

   a  b  c
0  1  2  3
1  2  3  4
2  3  4  5

crteating a data frame as ndarray

In [56]:
df5 = pd.DataFrame(np.arange(1,21).reshape(5,4),index=['r1','r2','r3','r4','r5'],columns = ['c1','c2','c3','c4'])
df5

    c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17  18  19  20

In [57]:
#in dict no need to provide the col names but in dataframe we have to give explicitly

creating a dataframe with series

In [64]:
d =pd.DataFrame(pd.Series([1,2,3,4,5],index = list('abcde')))
d

   0
a  1
b  2
c  3
d  4
e  5

In [68]:
ser1 = pd.Series([1,2,3,4,5],index=list('abcde'))
ser2 = pd.Series([6,7,8,9,0],index=list('fghij'))
ser3 = pd.Series([10,20,30,40,50],index=list('klmno'))
dct = {'col1':ser1,'col2':ser2,'col3':ser3}
dict1 =  pd.DataFrame(dict)
dict1

   a  b  c
0  1  2  3
1  2  3  4
2  3  4  5

In [70]:
ser1,ser2,ser3

(a    1
 b    2
 c    3
 d    4
 e    5
 dtype: int64,
 f    6
 g    7
 h    8
 i    9
 j    0
 dtype: int64,
 k    10
 l    20
 m    30
 n    40
 o    50
 dtype: int64)

In [71]:
dict2 = {"col1":{"a":1,"b":2,"c":3},
         "col2":{"d":4,"e":5,"f":6},
         "col3":{"g":7,"h":8,"i":9}}

In [72]:
dataframe = pd.DataFrame(dict2)
dataframe

   col1  col2  col3
a   1.0   NaN   NaN
b   2.0   NaN   NaN
c   3.0   NaN   NaN
d   NaN   4.0   NaN
e   NaN   5.0   NaN
f   NaN   6.0   NaN
g   NaN   NaN   7.0
h   NaN   NaN   8.0
i   NaN   NaN   9.0